[package]
name = "RustScan"
version = "0.1.0"
authors = ["Bee <brandon@skerritt.blog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.3"
clap = "2.33.0"
rayon = "1.3.1"
arrayvec = "0.5.1"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"